#! /usr/bin/env php
<?php
$db=new SQLite3("database/data.db");
if(!empty($_SERVER["argv"][1]) && !empty($_SERVER["argv"][2]) && !empty($_SERVER["argv"][3]) && !empty($_SERVER["argv"][4])){
  $stmt=$db->prepare("SELECT * FROM users WHERE user=:user");
  $stmt->bindValue(":user",$_SERVER["argv"][1]);
  if($stmt->execute()->fetchArray()){
    $stmt=$db->prepare("UPDATE users SET usergroup=:usergroup,department=:department,hash=:hash WHERE user=:user");
    $stmt->bindValue(":user", $_SERVER["argv"][1]);
    $stmt->bindValue(":usergroup", $_SERVER["argv"][2]);
    $stmt->bindValue(":department", $_SERVER["argv"][3]);
    $stmt->bindValue(":hash", password_hash($_SERVER["argv"][4], PASSWORD_DEFAULT));
    $stmt->execute();
  }
  else{
    $stmt=$db->prepare("INSERT INTO users (user,usergroup,department,hash) VALUES (:user,:usergroup,:department,:hash)");
    $stmt->bindValue(":user", $_SERVER["argv"][1]);
    $stmt->bindValue(":usergroup", $_SERVER["argv"][2]);
    $stmt->bindValue(":department", $_SERVER["argv"][3]);
    $stmt->bindValue(":hash", password_hash($_SERVER["argv"][4], PASSWORD_DEFAULT));
    $stmt->execute();
  }
}
else{
  echo basename(__FILE__)." [username] [usergroup] [department] [password]\n";
}
?>
